version: '2.2'
services:
  # Battlefield 2 1.5 server with bf2stats 2.3.3 python scripts
  bf2:
    image: startersclan/docker-bf2:v1.5.3153.0-bf2stats-2.3.3
    volumes:
      - ./config/bf2/mods/bf2/ai/aidefault-custom.ai:/server/bf2/mods/bf2/ai/aidefault.ai:ro # Customize bots
      - ./config/bf2/mods/bf2/ai/aibehaviours-fixlookatwrapper.ai:/server/bf2/mods/bf2/ai/aibehaviours.ai:ro # LoopAtWrapper fix
      # - ./config/bf2/mods/bf2/ai/aidefaultstrategies-custom-esai.ai:/server/bf2/mods/bf2/ai/aidefaultstrategies.ai:ro # Enable ESAI with a default strategy for all maps
      # - ./config/bf2/mods/bf2/ai/aidefaultstrategiesadd-custom-esai.ai:/server/bf2/mods/bf2/ai/aidefaultstrategiesadd.ai:ro # Enable ESAI with a default strategy for all maps
      - ./config/bf2/mods/bf2/settings/serversettings-custom.con:/server/bf2/mods/bf2/settings/serversettings.con:ro # Server config
      - ./config/bf2/mods/bf2/settings/maplist-custom-coop.con:/server/bf2/mods/bf2/settings/maplist.con:ro # Maplist
      - ./config/bf2/python/bf2/BF2StatisticsConfig-custom.py:/server/bf2/python/bf2/BF2StatisticsConfig.py:ro # bf2stats python config
    ports:
      - 16567:16567/udp
      - 29900:29900/udp
    networks:
      - gamespy-network
      - bf2-network
    extra_hosts:
      - battlefield2.available.gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - battlefield2.master.gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - battlefield2.ms14.gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - master.gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - motd.gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - gpsp.gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - gpcm.gamespy.com:92.51.181.102 # bf2hub.com master server IP
      - gamespy.com:92.51.181.102 # bf2hub.com master server IP
      # - bf2web.gamespy.com:192.168.1.100 # Our ASP web server IP. Use this if the ASP web server is running on a different host.
      # - gamestats.gamespy.com:192.168.1.100 # Our ASP web server IP. Use this if the ASP web server is running on a different host.
      # - eapusher.dice.se:192.168.1.100 # Our ASP web server IP. Use this if the ASP web server is running on a different host.
    depends_on:
      - asp-nginx
      - asp-php
    restart: unless-stopped
    tty: true
    stdin_open: true

  # The reverse proxy for our web containers
  # See https://github.com/traefik/traefik/tree/v2.7/docs/content/user-guides/docker-compose for some examples for enabling HTTPS using ACME
  # You will need a domain name. E.g. 'example.com'
  traefik:
    image: traefik:v2.7
    volumes:
      # Allow traefik to listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-acme-volume:/letsencrypt
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik-public-network
      - traefik-network
    restart: unless-stopped
    command:
      - --global.checknewversion=false
      # - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - "--certificatesresolvers.myresolver.acme.dnschallenge=true"
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=ovh"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=postmaster@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

  # The init container that sets up permissions for the asp and db volumes
  init-container:
    image: alpine:latest
    volumes:
      - ./config/ASP/config.php:/src/ASP/system/config/config.php
      - backups-volume:/src/ASP/system/database/backups # This volume is effectively unused since ASP doesn't allow DB backups for a remote DB, but mount it anyway to avoid errors.
      - logs-volume:/src/ASP/system/logs
      - snapshots-volume:/src/ASP/system/snapshots
      - bf2sclone-cache-volume:/src/bf2sclone/cache
      - db-volume:/var/lib/mysql
    entrypoint:
      - /bin/sh
    command:
      - -c
      - |
          set -eu

          echo "Granting ASP php write permissions"
          chmod 666 /src/ASP/system/config/config.php

          chown -R 82:82 /src/ASP/system/database/backups
          find /src/ASP/system/database/backups -type d -exec chmod 750 {} \;
          find /src/ASP/system/database/backups -type f -exec chmod 640 {} \;

          chown -R 82:82 /src/ASP/system/logs
          find /src/ASP/system/logs -type d -exec chmod 750 {} \;
          find /src/ASP/system/logs -type f -exec chmod 640 {} \;

          mkdir -p /src/ASP/system/snapshots/processed
          mkdir -p /src/ASP/system/snapshots/temp
          chown -R 82:82 /src/ASP/system/snapshots
          find /src/ASP/system/snapshots -type d -exec chmod 750 {} \;
          find /src/ASP/system/snapshots -type f -exec chmod 640 {} \;

          echo "Granting bf2sclone php write permissions"
          chown -R 82:82 /src/bf2sclone/cache
          find /src/bf2sclone/cache -type d -exec chmod 750 {} \;
          find /src/bf2sclone/cache -type f -exec chmod 640 {} \;

          echo "Granting db's 'mysql' user write permissions"
          chown -R 999:999 /var/lib/mysql

  # The gamespy ASP. The dashboard is available at https://asp.example.com/ASP
  asp-nginx:
    image: startersclan/bf2stats:2.3.3-asp-nginx
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME?err}_traefik-network"
      # traefik v2
      # http
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME?err}-asp-gamespy-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME?err}-asp-gamespy-http.rule=Host(`bf2web.gamespy.com`)" # Note: `bf2web.gamespy.com` doesn't need https. The BF2 client BFHQ, and the BF2 server python files, make a HTTP requests to `bf2web.gamespy.com` with `Host: bf2web.gamespy.com`.
      # http
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME?err}-asp-nginx-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME?err}-asp-nginx-http.rule=Host(`asp.example.com`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME?err}-asp-nginx-http.middlewares=${COMPOSE_PROJECT_NAME?err}-asp-nginx-http-myRedirectScheme" # Redirect http to https
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME?err}-asp-nginx-http-myRedirectScheme.redirectScheme.scheme=https" # Redirect http to https
      # https
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME?err}-asp-nginx.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME?err}-asp-nginx.tls"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME?err}-asp-nginx.rule=Host(`asp.example.com`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME?err}-asp-nginx.loadbalancer.server.port=80"
    # volumes:
    #   - ./config/ASP/nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Customize only if needed
    networks:
      traefik-network:
      bf2-network:
        aliases:
          - asp.example.com
          - bf2web.gamespy.com # Important! Spoof Gamespy DNS for the gameserver to reach our ASP server IP
          - gamestats.gamespy.com # Spoof Gamespy DNS for the gameserver to reach our ASP server IP. Doesn't seem to be used by the gameserver, but spoof anyway.
          - eapusher.dice.se  # Spoof Gamespy DNS for the gameserver to reach our ASP server IP. Doesn't seem to be used by the gameserver, but spoof anyway.
    depends_on:
      - init-container
      - asp-php
    restart: unless-stopped

  asp-php:
    image: startersclan/bf2stats:2.3.3-asp-php
    volumes:
      - ./config/ASP/config.php:/src/ASP/system/config/config.php # Main config file. Must be writeable or else ASP will throw an exception. Customize only if needed
      # - ./config/ASP/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini:ro  # Customize only if needed
      # - ./config/ASP/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro  # Customize only if needed
      - backups-volume:/src/ASP/system/database/backups # This volume is effectively unused since ASP doesn't allow DB backups for a remote DB, but mount it anyway to avoid errors.
      - logs-volume:/src/ASP/system/logs
      - snapshots-volume:/src/ASP/system/snapshots
    networks:
      - bf2-network
    depends_on:
      - init-container
    restart: unless-stopped

  # The bf2sclone for viewing BFHQ on the web. It is available at https://bf2sclone.example.com
  bf2sclone-nginx:
    image: startersclan/bf2stats:2.3.3-bf2sclone-nginx
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME?err}_traefik-network"
      # traefik v2
      # http
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME?err}-bf2sclone-nginx-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME?err}-bf2sclone-nginx-http.rule=Host(`bf2sclone.example.com`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME?err}-bf2sclone-nginx-http.middlewares=${COMPOSE_PROJECT_NAME?err}-bf2sclone-nginx-http-myRedirectScheme" # Redirect http to https
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME?err}-bf2sclone-nginx-http-myRedirectScheme.redirectScheme.scheme=https" # Redirect http to https
      # https
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME?err}-bf2sclone-nginx.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME?err}-bf2sclone-nginx.tls"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME?err}-bf2sclone-nginx.rule=Host(`bf2sclone.example.com`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME?err}-bf2sclone-nginx.loadbalancer.server.port=80"
    # volumes:
    #   - ./config/bf2sclone/nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Customize only if needed
    networks:
      - traefik-network
      - bf2-network
    depends_on:
      - init-container
      - bf2sclone-php
    restart: unless-stopped

  bf2sclone-php:
    image: startersclan/bf2stats:2.3.3-bf2sclone-php
    volumes:
      - ./config/bf2sclone/config.inc.php:/src/bf2sclone/config.inc.php:ro  # Main config file. Customize as needed
      # - ./config/bf2sclone/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini:ro  # Customize only if needed
      # - ./config/bf2sclone/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro  # Customize only if needed
      - bf2sclone-cache-volume:/src/bf2sclone/cache
    networks:
      - bf2-network
    depends_on:
      - init-container
    restart: unless-stopped

  # The DB container
  db:
    image: mariadb:10.8
    environment:
      - MARIADB_ROOT_PASSWORD=admin # Change this to a strong password.
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin # Change this to a strong password
      - MARIADB_DATABASE=bf2stats
    volumes:
      - ./config/db/my.cnf:/etc/my.cnf:ro # Customize as needed
      - db-volume:/var/lib/mysql
    networks:
      - bf2-network
    depends_on:
      - init-container
    restart: unless-stopped

  # The phpmyadmin interface for administrating the DB. It is available at phpmyadmin.example.com
  phpmyadmin:
    image: phpmyadmin:5.2
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME?err}_traefik-network"
      # traefik v2
      # http
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME?err}-phpmyadmin-http.entrypoints=web"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME?err}-phpmyadmin-http.rule=Host(`phpmyadmin.example.com`)"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME?err}-phpmyadmin-http.middlewares=${COMPOSE_PROJECT_NAME?err}-phpmyadmin-http-myRedirectScheme" # Redirect http to https
      - "traefik.http.middlewares.${COMPOSE_PROJECT_NAME?err}-phpmyadmin-http-myRedirectScheme.redirectScheme.scheme=https" # Redirect http to https
      # https
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME?err}-phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME?err}-phpmyadmin.tls"
      - "traefik.http.routers.${COMPOSE_PROJECT_NAME?err}-phpmyadmin.rule=Host(`phpmyadmin.example.com`)"
      - "traefik.http.services.${COMPOSE_PROJECT_NAME?err}-phpmyadmin.loadbalancer.server.port=80"
    environment:
      - PMA_ABSOLUTE_URI=https://phpmyadmin.example.com # Enable this if behind a reverse proxy
      - PMA_HOST=db
    networks:
      - traefik-network
      - bf2-network
    restart: unless-stopped

networks:
  gamespy-network:
  bf2-network:
  traefik-public-network:
  traefik-network:
    internal: true

volumes:
  prmasterserver-volume:
  traefik-acme-volume:
  backups-volume:
  logs-volume:
  snapshots-volume:
  bf2sclone-cache-volume:
  db-volume:
